-- Used for mod config overwrites. Those files should be located in an identical folder structure within that mod.
--
-- Uncomment to disable allied support teammates (friendly waves only; enemy support stays on):
-- enableAlliedSupport = 0