{difficulty
	(include "difficulty_generic.inc")
	{any	;// temp to give enemy stats
		{health 0.33}
		{accuracy 0.95}
		{grenade_timeout 16.00}
		{burst 0.75}
	}
	{enemy	;// not working in coop
		{health 1.0}
		{accuracy 0.95}
		{grenade_timeout 16.00}
		{burst 0.75}
	}
	{ally
		{health 1.50}
		{accuracy 0.95}
		{grenade_timeout 16.00}
		{burst 0.75}
	}
	{player
		{health 2.00}
		{accuracy 0.95}	
		{grenade_timeout 16.00}
		{burst 0.75}
	}

}