				{chargeFactors
					{value "*=1.0"}
				}
				{commandPoints "*=0:125,900:150,1500:200"}
				{budgets
					{vehicle
						{mode "with_update"}
						{resource
							{start		500}
							{finish		2000}
							{speed 		500}
							{period 	180}
						}
						{buttons "player division"}
					}
					{hero
						{resource
							{start		50}
							{finish		100}
							{speed 		25}
							{period 	480}
						}
						{buttons "support"}
						{tag "special"}
					}
				}