#!/usr/bin/env python3
"""Deploy ordinary AI troop transports across all four support quadrants.

Exactly one friendly and one enemy transport can be active in a mission:

* player attacks:  friendly attack-support + enemy defender
* player defends:  friendly defender + enemy attacker

The transports retain linked passengers and rely entirely on ordinary game AI to
unload under contact. No timed emit, turnaround, withdrawal, deletion, or cleanup
is added. Each hull rotates through generated flag-perimeter waypoints while its
passengers remain within mounted distance of the truck.
"""
from __future__ import annotations

import argparse
import math
import re
from dataclasses import dataclass
from pathlib import Path


class PatchError(RuntimeError):
    pass


ENGINE_BEGIN = "; BEGIN FOUR-QUADRANT NORMAL TRANSPORT PATROL — {key}"
ENGINE_END = "; END FOUR-QUADRANT NORMAL TRANSPORT PATROL — {key}"
PACKAGE_BEGIN = "; BEGIN ENEMY NORMAL TRANSPORT PACKAGES"
PACKAGE_END = "; END ENEMY NORMAL TRANSPORT PACKAGES"
TAG_BEGIN = "; BEGIN ENEMY NORMAL TRANSPORT TAGS"
TAG_END = "; END ENEMY NORMAL TRANSPORT TAGS"
VARS_BEGIN = "; BEGIN FOUR-QUADRANT NORMAL TRANSPORT VARS"
VARS_END = "; END FOUR-QUADRANT NORMAL TRANSPORT VARS"

# Sections generated by the superseded two-truck comparison overlay.
OLD_MARKER_PAIRS = (
    (
        "; BEGIN TRANSPORT CONTROL COMPARISON PACKAGES",
        "; END TRANSPORT CONTROL COMPARISON PACKAGES",
    ),
    (
        "; BEGIN TRANSPORT CONTROL COMPARISON TAGS",
        "; END TRANSPORT CONTROL COMPARISON TAGS",
    ),
    (
        "; BEGIN FRIENDLY NORMAL-COMBAT TRANSPORT CONTROL",
        "; END FRIENDLY NORMAL-COMBAT TRANSPORT CONTROL",
    ),
    (
        "; BEGIN ENEMY NORMAL-COMBAT TRANSPORT CONTROL",
        "; END ENEMY NORMAL-COMBAT TRANSPORT CONTROL",
    ),
)

FILES = (
    "attack_support_waves.inc",
    "enemy_defense_support.inc",
    "defense_support_waves.inc",
    "enemy_attack_support.inc",
    "faction_support_templates.inc",
    "dcg_vars.inc",
)

FACTIONS = {
    "rusa": {
        "army": 1,
        "source_start": 0xB3A0,
        "source_package": "ally_sup_rusa_motor",
        "source_hull": "ally_sup_rusa_motor_hull",
        "source_pax": "ally_sup_rusa_motor_pax",
        "enemy_start": 0xB600,
        "enemy_mid": 10000,
    },
    "ukr": {
        "army": 2,
        "source_start": 0xB3AB,
        "source_package": "ally_sup_ukr_motor",
        "source_hull": "ally_sup_ukr_motor_hull",
        "source_pax": "ally_sup_ukr_motor_pax",
        "enemy_start": 0xB60B,
        "enemy_mid": 10011,
    },
    "nato": {
        "army": 3,
        "source_start": 0xB3B6,
        "source_package": "ally_sup_nato_motor",
        "source_hull": "ally_sup_nato_motor_hull",
        "source_pax": "ally_sup_nato_motor_pax",
        "enemy_start": 0xB616,
        "enemy_mid": 10022,
    },
    "prc": {
        "army": 4,
        "source_start": 0xB3C1,
        "source_package": "ally_sup_prc_motor",
        "source_hull": "ally_sup_prc_motor_hull",
        "source_pax": "ally_sup_prc_motor_pax",
        "enemy_start": 0xB621,
        "enemy_mid": 10033,
    },
}


@dataclass(frozen=True)
class Engine:
    key: str
    filename: str
    trigger_ns: str
    user_is_defender: int
    armed_var: str
    army_var: str
    owner_id_var: str
    owner_macro: str
    deploy_tag: str
    hull_tag: str
    pax_tag: str
    done_var: str
    step_var: str
    friendly_package: bool
    same_side_as_enemy: bool
    start_step: int
    anchor: str


ENGINES = (
    Engine(
        key="as",
        filename="attack_support_waves.inc",
        trigger_ns="attack_support",
        user_is_defender=0,
        armed_var="attack_support_armed",
        army_var="faction_support_army",
        owner_id_var="id_attack_support",
        owner_macro="am_own_to_support",
        deploy_tag="attack_support_deploy",
        hull_tag="transport_as_hull",
        pax_tag="transport_as_pax",
        done_var="transport_as_done",
        step_var="transport_as_step",
        friendly_package=True,
        same_side_as_enemy=False,
        start_step=1,
        anchor='{"attack_support/motor_cleanup"',
    ),
    Engine(
        key="ed",
        filename="enemy_defense_support.inc",
        trigger_ns="enemy_defense",
        user_is_defender=0,
        armed_var="enemy_defense_armed",
        army_var="enemy_defense_army",
        owner_id_var="id_1st_enemy",
        owner_macro="ed_own_to_enemy",
        deploy_tag="enemy_def_deploy",
        hull_tag="transport_ed_hull",
        pax_tag="transport_ed_pax",
        done_var="transport_ed_done",
        step_var="transport_ed_step",
        friendly_package=False,
        same_side_as_enemy=True,
        start_step=3,
        anchor='{"enemy_defense/patrol_1"',
    ),
    Engine(
        key="ds",
        filename="defense_support_waves.inc",
        trigger_ns="defense_support",
        user_is_defender=1,
        armed_var="defense_support_armed",
        army_var="faction_support_army",
        owner_id_var="id_defenderbot",
        owner_macro="ds_own_to_defenderbot",
        deploy_tag="def_sup_deploy",
        hull_tag="transport_ds_hull",
        pax_tag="transport_ds_pax",
        done_var="transport_ds_done",
        step_var="transport_ds_step",
        friendly_package=True,
        same_side_as_enemy=False,
        start_step=1,
        anchor='{"defense_support/motor_cleanup"',
    ),
    Engine(
        key="ea",
        filename="enemy_attack_support.inc",
        trigger_ns="enemy_attack",
        user_is_defender=1,
        armed_var="enemy_attack_armed",
        army_var="enemy_attack_army",
        owner_id_var="id_1st_enemy",
        owner_macro="ea_own_to_enemy",
        deploy_tag="ea_deploy",
        hull_tag="transport_ea_hull",
        pax_tag="transport_ea_pax",
        done_var="transport_ea_done",
        step_var="transport_ea_step",
        friendly_package=False,
        same_side_as_enemy=True,
        start_step=3,
        anchor='{"enemy_attack/motor_cleanup"',
    ),
)


def balanced_end(text: str, start: int, opener: str, closer: str, label: str) -> int:
    depth = 0
    quoted = False
    escaped = False
    for index in range(start, len(text)):
        char = text[index]
        if quoted:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                quoted = False
            continue
        if char == '"':
            quoted = True
        elif char == opener:
            depth += 1
        elif char == closer:
            depth -= 1
            if depth == 0:
                return index + 1
    raise PatchError(f"Unbalanced block: {label}")


def marked_bounds(text: str, begin: str, end: str) -> tuple[int, int] | None:
    begin_at = text.find(begin)
    if begin_at < 0:
        return None
    end_at = text.find(end, begin_at)
    if end_at < 0:
        raise PatchError(f"Existing section {begin} has no end marker")
    start = text.rfind("\n", 0, begin_at) + 1
    finish = text.find("\n", end_at)
    finish = len(text) if finish < 0 else finish + 1
    return start, finish


def strip_marked(text: str, begin: str, end: str) -> str:
    bounds = marked_bounds(text, begin, end)
    if not bounds:
        return text
    return text[: bounds[0]] + text[bounds[1] :]


def upsert_before(text: str, begin: str, end: str, section: str, anchor: str) -> str:
    rendered = section.rstrip() + "\n"
    bounds = marked_bounds(text, begin, end)
    if bounds:
        return text[: bounds[0]] + rendered + text[bounds[1] :]
    anchor_at = text.find(anchor)
    if anchor_at < 0:
        raise PatchError(f"Missing insertion anchor for {begin}: {anchor}")
    line_start = text.rfind("\n", 0, anchor_at) + 1
    return text[:line_start] + rendered + "\n" + text[line_start:]


def remove_trigger(text: str, name: str) -> str:
    marker = f'{{"{name}"'
    start = text.find(marker)
    if start < 0:
        return text
    block_start = start
    while block_start > 0 and text[block_start - 1] in "\t ":
        block_start -= 1
    end = balanced_end(text, start, "{", "}", name)
    while end < len(text) and text[end] in "\r\n":
        end += 1
    return text[:block_start] + text[end:]


def idempotent_replace(text: str, old: str, new: str, label: str) -> str:
    old_count = text.count(old)
    new_count = text.count(new)
    if old_count == 1 and new_count == 0:
        return text.replace(old, new, 1)
    if old_count == 0 and new_count == 1:
        return text
    raise PatchError(
        f"{label}: expected one original or one patched occurrence; "
        f"found old={old_count}, new={new_count}"
    )


def extract_entity(text: str, entity_id: int) -> str:
    token = f"0x{entity_id:x}"
    match = re.search(r'\{(?:Entity|Human)\s+"[^"]+"\s+' + re.escape(token) + r'\b', text)
    if not match:
        raise PatchError(f"Missing source motor entity {token}")
    end = balanced_end(text, match.start(), "{", "}", token)
    return text[match.start() : end]


def render_enemy_packages(text: str) -> str:
    blocks: list[str] = [PACKAGE_BEGIN]
    links: list[str] = []
    tags: list[str] = [TAG_BEGIN]

    for faction, cfg in FACTIONS.items():
        source_start = int(cfg["source_start"])
        enemy_start = int(cfg["enemy_start"])
        enemy_mid = int(cfg["enemy_mid"])
        id_map = {
            source_start + offset: enemy_start + offset for offset in range(11)
        }
        blocks.append(f"; ----- ENEMY NORMAL {faction.upper()} TRANSPORT -----")
        for offset in range(11):
            source_id = source_start + offset
            block = extract_entity(text, source_id)
            for old_id, new_id in id_map.items():
                block = re.sub(
                    rf"\b0x{old_id:x}\b", f"0x{new_id:x}", block, flags=re.IGNORECASE
                )
            block = re.sub(
                r"\{MID\s+\d+\}", f"{{MID {enemy_mid + offset}}}", block, count=1
            )
            blocks.append(block)

        hull = enemy_start
        links.append(f'\t{{Link 0x{hull + 1:x} {{0x{hull:x} "driver"}}}}')
        links.append(f'\t{{Link 0x{hull + 2:x} {{0x{hull:x} "commander"}}}}')
        for seat in range(1, 9):
            links.append(
                f'\t{{Link 0x{hull + 2 + seat:x} {{0x{hull:x} "seat{seat}"}}}}'
            )

        package = f"transport_enemy_{faction}"
        for offset in range(11):
            entity = enemy_start + offset
            role = (
                f"{package}_hull"
                if offset == 0
                else (f"{package}_crew" if offset <= 2 else f"{package}_pax")
            )
            tags.append(
                f'\t{{Tags "transport_enemy_tpl" "{package}" "{role}" "hidden" 0x{entity:x}}}'
            )

    blocks.extend(links)
    blocks.append(PACKAGE_END)
    tags.append(TAG_END)
    return "\n".join(blocks), "\n".join(tags)


def patch_templates(text: str) -> str:
    for begin, end in OLD_MARKER_PAIRS[:2]:
        text = strip_marked(text, begin, end)
    packages, tags = render_enemy_packages(text)
    text = upsert_before(
        text,
        PACKAGE_BEGIN,
        PACKAGE_END,
        packages,
        "; ===== E2 AIR PACKAGE POOLS",
    )
    return upsert_before(
        text,
        TAG_BEGIN,
        TAG_END,
        tags,
        '\t{Tags "ally_sup_tpl" "support_e2_tpl"',
    )


def render_place(engine: Engine) -> str:
    if engine.same_side_as_enemy:
        side1, side2, fallback = "a1", "b1", "a1"
    else:
        side1, side2, fallback = "b1", "a1", "b1"
    return f'''\t\t\t(define "transport_{engine.key}_place"
\t\t\t\t{{"switch"
\t\t\t\t\t{{"case"
\t\t\t\t\t\t{{condition {{type cmp_i}} {{var "enemy_spawnside$"}} {{op "=="}} {{value 1}}}}
\t\t\t\t\t\t{{"placement"
\t\t\t\t\t\t\t{{selector {{ignore_captured_by_user 0}} {{tag {engine.deploy_tag}}}}}
\t\t\t\t\t\t\t{{target_waypoint "attack_support_entry_{side1}"}}
\t\t\t\t\t\t}}
\t\t\t\t\t}}
\t\t\t\t\t{{"case"
\t\t\t\t\t\t{{condition {{type cmp_i}} {{var "enemy_spawnside$"}} {{op "=="}} {{value 2}}}}
\t\t\t\t\t\t{{"placement"
\t\t\t\t\t\t\t{{selector {{ignore_captured_by_user 0}} {{tag {engine.deploy_tag}}}}}
\t\t\t\t\t\t\t{{target_waypoint "attack_support_entry_{side2}"}}
\t\t\t\t\t\t}}
\t\t\t\t\t}}
\t\t\t\t\t{{"default"
\t\t\t\t\t\t{{"placement"
\t\t\t\t\t\t\t{{selector {{ignore_captured_by_user 0}} {{tag {engine.deploy_tag}}}}}
\t\t\t\t\t\t\t{{target_waypoint "attack_support_entry_{fallback}"}}
\t\t\t\t\t\t}}
\t\t\t\t\t}}
\t\t\t\t}}
\t\t\t)'''


def render_issue_patrol(engine: Engine) -> str:
    cases: list[str] = []
    for step in range(1, 6):
        next_step = 1 if step == 5 else step + 1
        cases.append(
            f'''\t\t\t\t\t{{"case"
\t\t\t\t\t\t{{condition {{type cmp_i}} {{var "{engine.step_var}$"}} {{op "=="}} {{value {step}}}}}
\t\t\t\t\t\t{{"action"
\t\t\t\t\t\t\t{{selector {{ignore_captured_by_user 0}} {{tag {engine.hull_tag}}}}}
\t\t\t\t\t\t\t{{drop orders}}
\t\t\t\t\t\t\t{{action move}}
\t\t\t\t\t\t\t{{waypoint "transport_patrol_flag_{step}"}}
\t\t\t\t\t\t}}
\t\t\t\t\t\t{{"set_i" {{var "{engine.step_var}$"}} {{op "="}} {{value {next_step}}}}}
\t\t\t\t\t}}'''
        )
    return f'''\t\t\t(define "transport_{engine.key}_issue_patrol"
\t\t\t\t{{"switch"
{chr(10).join(cases)}
\t\t\t\t\t{{"default"
\t\t\t\t\t\t{{"set_i" {{var "{engine.step_var}$"}} {{op "="}} {{value 1}}}}
\t\t\t\t\t}}
\t\t\t\t}}
\t\t\t)'''


def source_tags(faction: str, engine: Engine) -> tuple[str, str, str, str]:
    cfg = FACTIONS[faction]
    if engine.friendly_package:
        return (
            str(cfg["source_package"]),
            str(cfg["source_hull"]),
            str(cfg["source_pax"]),
            "ally_sup_tpl",
        )
    package = f"transport_enemy_{faction}"
    return package, f"{package}_hull", f"{package}_pax", "transport_enemy_tpl"


def render_dispatch(engine: Engine, faction: str) -> str:
    cfg = FACTIONS[faction]
    package, source_hull, source_pax, template_tag = source_tags(faction, engine)
    return f'''\t\t\t{{"{engine.trigger_ns}/normal_transport_{faction}"
\t\t\t\t{{condition
\t\t\t\t\t{{expression "1 & 2 & 3 & 4 & 5 & 6"}}
\t\t\t\t\t{{terms
\t\t\t\t\t\t{{"1.cmp_i" {{var "user_is_defender$"}} {{op "=="}} {{value {engine.user_is_defender}}}}}
\t\t\t\t\t\t{{"2.cmp_i" {{var "{engine.armed_var}$"}} {{op "=="}} {{value 1}}}}
\t\t\t\t\t\t{{"3.cmp_i" {{var "{engine.army_var}$"}} {{op "=="}} {{value {cfg['army']}}}}}
\t\t\t\t\t\t{{"4.cmp_i" {{var "{engine.owner_id_var}$"}} {{op ">"}} {{value 0}}}}
\t\t\t\t\t\t{{"5.cmp_i" {{var "{engine.done_var}$"}} {{op "=="}} {{value 0}}}}
\t\t\t\t\t\t{{"6.entities" {{selector {{tag {source_hull}}}} {{count {{op ">="}} {{value 1}}}}}}
\t\t\t\t\t}}
\t\t\t\t}}
\t\t\t\t{{actions
\t\t\t\t\t{{"set_i" {{var "{engine.done_var}$"}} {{op "="}} {{value 1}}}}
\t\t\t\t\t{{"delay" {{time 45}}}}
\t\t\t\t\t{{"entity_state"
\t\t\t\t\t\t{{selector {{source advanced}} {{group {{select {{tag {{tag {package}}}}}}}}}}}
\t\t\t\t\t\t{{tag_add {engine.deploy_tag}}}
\t\t\t\t\t}}
\t\t\t\t\t{{"entity_state"
\t\t\t\t\t\t{{selector {{source advanced}} {{group {{select {{tag {{tag {source_hull}}}}}}}}}}}
\t\t\t\t\t\t{{tag_add {engine.hull_tag}}}
\t\t\t\t\t}}
\t\t\t\t\t{{"entity_state"
\t\t\t\t\t\t{{selector {{source advanced}} {{group {{select {{tag {{tag {source_pax}}}}}}}}}}}
\t\t\t\t\t\t{{tag_add {engine.pax_tag}}}
\t\t\t\t\t}}
\t\t\t\t\t("transport_{engine.key}_place")
\t\t\t\t\t{{"entity_state"
\t\t\t\t\t\t{{selector {{ignore_captured_by_user 0}} {{tag {engine.deploy_tag}}}}}
\t\t\t\t\t\t{{tag_remove {template_tag}}}
\t\t\t\t\t\t{{tag_remove {package}}}
\t\t\t\t\t\t{{tag_remove hidden}}
\t\t\t\t\t\t{{inactive off}}
\t\t\t\t\t\t{{impregnability disabled}}
\t\t\t\t\t\t{{discovered on}}
\t\t\t\t\t}}
\t\t\t\t\t{{"delay" {{time 0.2}}}}
\t\t\t\t\t("{engine.owner_macro}")
\t\t\t\t\t{{"delay" {{time 0.4}}}}
\t\t\t\t\t{{"actor_state"
\t\t\t\t\t\t{{selector {{ignore_captured_by_user 0}} {{tag {engine.deploy_tag}}}}}
\t\t\t\t\t\t{{control AI}}
\t\t\t\t\t\t{{ai_move {{mode enable}}}}
\t\t\t\t\t\t{{weapon_prepare on}}
\t\t\t\t\t\t{{fire_mode open}}
\t\t\t\t\t\t{{move_mode free}}
\t\t\t\t\t\t{{movement {{speed normal}} {{kind normal}} {{type normal}}}}
\t\t\t\t\t\t{{ai {{no_retreat off}} {{advance_ratio 1}} {{retreat_ratio 0}}}}
\t\t\t\t\t}}
\t\t\t\t\t{{"set_i" {{var "{engine.step_var}$"}} {{op "="}} {{value {engine.start_step}}}}}
\t\t\t\t\t("transport_{engine.key}_issue_patrol")
\t\t\t\t\t{{"entity_state"
\t\t\t\t\t\t{{selector {{tag {engine.deploy_tag}}}}
\t\t\t\t\t\t{{tag_remove {engine.deploy_tag}}}
\t\t\t\t\t}}
\t\t\t\t\t{{"delay" {{time 45}}}}
\t\t\t\t\t{{"trigger" {{name "{engine.trigger_ns}/normal_transport_patrol"}}}}
\t\t\t\t}}
\t\t\t}}'''


def render_patrol_trigger(engine: Engine) -> str:
    return f'''\t\t\t; Route continues only while at least one tagged passenger remains within
\t\t\t; eight metres of the hull. Normal AI dismount under contact breaks that
\t\t\t; proximity and therefore stops all further scripted route orders.
\t\t\t{{"{engine.trigger_ns}/normal_transport_patrol"
\t\t\t\t{{condition
\t\t\t\t\t{{expression "1 & 2 & 3 & 4"}}
\t\t\t\t\t{{terms
\t\t\t\t\t\t{{"1.cmp_i" {{var "user_is_defender$"}} {{op "=="}} {{value {engine.user_is_defender}}}}}
\t\t\t\t\t\t{{"2.cmp_i" {{var "{engine.done_var}$"}} {{op "=="}} {{value 1}}}}
\t\t\t\t\t\t{{"3.entities" {{selector {{tag {engine.hull_tag}}} {{state operatable}}}} {{count {{op ">="}} {{value 1}}}}}}
\t\t\t\t\t\t{{"4.near"
\t\t\t\t\t\t\t{{units {{ignore_captured_by_user 0}} {{tag {engine.pax_tag}}} {{state operatable}}}}
\t\t\t\t\t\t\t{{near_to {{ignore_captured_by_user 0}} {{tag {engine.hull_tag}}} {{state operatable}}}}
\t\t\t\t\t\t\t{{distance 80}}
\t\t\t\t\t\t}}
\t\t\t\t\t}}
\t\t\t\t}}
\t\t\t\t{{actions
\t\t\t\t\t("transport_{engine.key}_issue_patrol")
\t\t\t\t\t{{"delay" {{time 45}}}}
\t\t\t\t\t{{"trigger" {{name "{engine.trigger_ns}/normal_transport_patrol"}}}}
\t\t\t\t}}
\t\t\t}}'''


def render_engine(engine: Engine) -> str:
    begin = ENGINE_BEGIN.format(key=engine.key.upper())
    end = ENGINE_END.format(key=engine.key.upper())
    parts = [
        begin,
        "\t\t\t; Ordinary combat transport: no timed emit, turnaround, withdrawal,",
        "\t\t\t; deletion, or cleanup. Route targets flag-perimeter waypoints only.",
        render_place(engine),
        render_issue_patrol(engine),
    ]
    parts.extend(render_dispatch(engine, faction) for faction in FACTIONS)
    parts.extend((render_patrol_trigger(engine), end))
    return "\n\n".join(parts)


def patch_engine(text: str, engine: Engine) -> str:
    # Remove superseded two-truck controls if this overlay is applied without the
    # baseline wrapper first.
    for begin, end in OLD_MARKER_PAIRS[2:]:
        text = strip_marked(text, begin, end)

    # Disable every timer-driven motor dispatch. Helper macros remain harmless and
    # are useful historical reference, but no old motor trigger has a live budget.
    if engine.key == "as":
        text = remove_trigger(text, "attack_support/motor_test")
        text = idempotent_replace(
            text,
            '{"set_i" {var "attack_support_motor_left$"} {op "="} {value 1}}',
            '{"set_i" {var "attack_support_motor_left$"} {op "="} {value 0}}',
            "friendly attacker scripted motor budget",
        )
        text = idempotent_replace(
            text,
            '{"set_i" {var "attack_support_motor_test$"} {op "="} {value 1}}',
            '{"set_i" {var "attack_support_motor_test$"} {op "="} {value 0}}',
            "friendly attacker forced motor mode",
        )
    elif engine.key == "ds":
        text = remove_trigger(text, "defense_support/motor_test")
    elif engine.key == "ea":
        text = remove_trigger(text, "enemy_attack/motor_test")
        text = idempotent_replace(
            text,
            '{"set_i" {var "enemy_attack_motor_left$"} {op "="} {value 1}}',
            '{"set_i" {var "enemy_attack_motor_left$"} {op "="} {value 0}}',
            "enemy attacker scripted motor budget",
        )
        text = idempotent_replace(
            text,
            '{"set_i" {var "enemy_attack_motor_test$"} {op "="} {value 1}}',
            '{"set_i" {var "enemy_attack_motor_test$"} {op "="} {value 0}}',
            "enemy attacker forced motor mode",
        )

    begin = ENGINE_BEGIN.format(key=engine.key.upper())
    end = ENGINE_END.format(key=engine.key.upper())
    return upsert_before(text, begin, end, render_engine(engine), engine.anchor)


def patch_vars(text: str) -> str:
    # Remove the superseded comparison-only vars when present.
    text = re.sub(r'^[ \t]*\{"motor_compare_(?:friend|enemy)_done"\}\r?\n', '', text, flags=re.MULTILINE)
    vars_lines = [VARS_BEGIN]
    for engine in ENGINES:
        vars_lines.append(f'\t\t\t{{"{engine.done_var}"}}')
        vars_lines.append(f'\t\t\t{{"{engine.step_var}"}}')
    vars_lines.append(VARS_END)
    section = "\n".join(vars_lines)
    bounds = marked_bounds(text, VARS_BEGIN, VARS_END)
    if bounds:
        return text[: bounds[0]] + section + "\n" + text[bounds[1] :]
    anchor = '\t\t\t{"enemy_attack_motor_test_done"}'
    if text.count(anchor) != 1:
        raise PatchError("dcg_vars transport insertion anchor is not unique")
    return text.replace(anchor, anchor + "\n" + section, 1)


def read_text(path: Path) -> tuple[str, bool]:
    raw = path.read_bytes()
    return raw.decode("utf-8-sig"), raw.startswith(b"\xef\xbb\xbf")


def write_text(path: Path, text: str, bom: bool) -> None:
    raw = text.encode("utf-8")
    path.write_bytes((b"\xef\xbb\xbf" if bom else b"") + raw)


def validate_engine(text: str, engine: Engine) -> None:
    begin = ENGINE_BEGIN.format(key=engine.key.upper())
    end = ENGINE_END.format(key=engine.key.upper())
    bounds = marked_bounds(text, begin, end)
    if not bounds:
        raise PatchError(f"Missing transport section for {engine.key}")
    block = text[bounds[0] : bounds[1]]

    for faction in FACTIONS:
        trigger = f'{{"{engine.trigger_ns}/normal_transport_{faction}"'
        if block.count(trigger) != 1:
            raise PatchError(f"{engine.key}: missing or duplicate {faction} dispatch")
    if block.count(f'{{"{engine.trigger_ns}/normal_transport_patrol"') != 1:
        raise PatchError(f"{engine.key}: patrol trigger missing or duplicated")
    for step in range(1, 6):
        if f'{{waypoint "transport_patrol_flag_{step}"}}' not in block:
            raise PatchError(f"{engine.key}: route waypoint {step} is missing")
    for token in (
        '{action move}',
        '{distance 80}',
        f'{{tag {engine.hull_tag}}}',
        f'{{tag {engine.pax_tag}}}',
        f'("{engine.owner_macro}")',
        '{"delay" {time 45}}',
    ):
        if token not in block:
            raise PatchError(f"{engine.key}: normal transport section missing {token}")
    for forbidden in (
        '{"emit"',
        '{mode passengers}',
        'exit_motor_to_origin',
        'motor_leaving',
        '{"delete"',
        '{"delay" {time 75}}',
    ):
        if forbidden in block:
            raise PatchError(f"{engine.key}: normal transport contains {forbidden}")


def validate(root: Path) -> None:
    multi = root / "resource/map/multi"
    templates = (multi / "faction_support_templates.inc").read_text(encoding="utf-8-sig")
    variables = (multi / "dcg_vars.inc").read_text(encoding="utf-8-sig")

    for marker in (PACKAGE_BEGIN, PACKAGE_END, TAG_BEGIN, TAG_END):
        if templates.count(marker) != 1:
            raise PatchError(f"Template marker count invalid: {marker}")
    for faction, cfg in FACTIONS.items():
        start = int(cfg["enemy_start"])
        if templates.count(f"0x{start:x}") < 2:
            raise PatchError(f"Enemy {faction} transport hull or link is missing")
        for seat in range(1, 9):
            if f'{{0x{start:x} "seat{seat}"}}' not in templates:
                raise PatchError(f"Enemy {faction} seat{seat} link is missing")
        package = f"transport_enemy_{faction}"
        if templates.count(f'"{package}"') < 11:
            raise PatchError(f"Enemy {faction} package tags are incomplete")

    for engine in ENGINES:
        text = (multi / engine.filename).read_text(encoding="utf-8-sig")
        validate_engine(text, engine)

    attack = (multi / "attack_support_waves.inc").read_text(encoding="utf-8-sig")
    defense = (multi / "defense_support_waves.inc").read_text(encoding="utf-8-sig")
    enemy_attack = (multi / "enemy_attack_support.inc").read_text(encoding="utf-8-sig")
    if '{"attack_support/motor_test"' in attack:
        raise PatchError("Old friendly-attacker timed motor trigger is still active")
    if '{"defense_support/motor_test"' in defense:
        raise PatchError("Old friendly-defender timed motor trigger is still active")
    if '{"enemy_attack/motor_test"' in enemy_attack:
        raise PatchError("Old enemy-attacker timed motor trigger is still active")
    for text, var in (
        (attack, "attack_support_motor_left"),
        (attack, "attack_support_motor_test"),
        (enemy_attack, "enemy_attack_motor_left"),
        (enemy_attack, "enemy_attack_motor_test"),
    ):
        token = f'{{"set_i" {{var "{var}$"}} {{op "="}} {{value 0}}}}'
        if text.count(token) != 1:
            raise PatchError(f"Scripted motor disablement missing: {var}")

    for engine in ENGINES:
        for var in (engine.done_var, engine.step_var):
            if variables.count(f'{{"{var}"}}') != 1:
                raise PatchError(f"Transport var missing or duplicated: {var}")


def apply(root: Path, *, check_only: bool = False) -> list[Path]:
    multi = root / "resource/map/multi"
    paths = {name: multi / name for name in FILES}
    for path in paths.values():
        if not path.is_file():
            raise PatchError(f"Missing required file: {path}")

    results: dict[str, tuple[str, bool]] = {}
    changed: list[Path] = []
    engine_by_file = {engine.filename: engine for engine in ENGINES}

    for name, path in paths.items():
        text, bom = read_text(path)
        if name == "faction_support_templates.inc":
            patched = patch_templates(text)
        elif name == "dcg_vars.inc":
            patched = patch_vars(text)
        else:
            patched = patch_engine(text, engine_by_file[name])
        results[name] = (patched, bom)
        if patched != text:
            changed.append(path)

    if not check_only:
        for name, (patched, bom) in results.items():
            write_text(paths[name], patched, bom)
        validate(root)
    return changed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        validate(args.root)
        print("Four-quadrant normal transport patrols validated.")
    else:
        changed = apply(args.root)
        print(f"Four-quadrant normal transport patrol patched {len(changed)} file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
