			{"default_spawns"
				{"spawn"
					{entity "conquest_spawn_helper"}
					{waypoint "0"}
					{disable_random_spawn_position}
				}
				{"delay"
					{time 0.01}
				}
				{"entity_state"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{amount 1
						}
						{tag conquest_spawn_helper}
					}
					{tag_add _default_a1}
					{tag_remove conquest_spawn_helper}
				}
				{"delay"
					{time 0.05}
				}
				{"placement"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{tag _default_a1}
					}
					{target
						{ignore_captured_by_user 0}
						{tag a1}
					}
				}
				{"spawn"
					{entity "conquest_spawn_helper"}
					{waypoint "0"}
					{disable_random_spawn_position}
				}
				{"delay"
					{time 0.01}
				}
				{"entity_state"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{amount 1
						}
						{tag conquest_spawn_helper}
					}
					{tag_add _default_a2}
					{tag_remove conquest_spawn_helper}
				}
				{"delay"
					{time 0.01}
				}
				{"placement"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{tag _default_a2}
					}
					{target
						{ignore_captured_by_user 0}
						{tag a2}
					}
				}
				{"spawn"
					{entity "conquest_spawn_helper"}
					{waypoint "0"}
					{disable_random_spawn_position}
				}
				{"delay"
					{time 0.01}
				}
				{"entity_state"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{amount 1
						}
						{tag conquest_spawn_helper}
					}
					{tag_add _default_a3}
					{tag_remove conquest_spawn_helper}
				}
				{"delay"
					{time 0.05}
				}
				{"placement"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{tag _default_a3}
					}
					{target
						{ignore_captured_by_user 0}
						{tag a3}
					}
				}
				{"spawn"
					{entity "conquest_spawn_helper"}
					{waypoint "0"}
					{disable_random_spawn_position}
				}
				{"delay"
					{time 0.01}
				}
				{"entity_state"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{amount 1
						}
						{tag conquest_spawn_helper}
					}
					{tag_add _default_a4}
					{tag_remove conquest_spawn_helper}
				}
				{"delay"
					{time 0.05}
				}
				{"placement"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{tag _default_a4}
					}
					{target
						{ignore_captured_by_user 0}
						{tag a4}
					}
				}
				{"spawn"
					{entity "conquest_spawn_helper"}
					{waypoint "0"}
					{disable_random_spawn_position}
				}
				{"delay"
					{time 0.01}
				}
				{"entity_state"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{amount 1
						}
						{tag conquest_spawn_helper}
					}
					{tag_add _default_b1}
					{tag_remove conquest_spawn_helper}
				}
				{"delay"
					{time 0.05}
				}
				{"placement"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{tag _default_b1}
					}
					{target
						{ignore_captured_by_user 0}
						{tag b1}
					}
				}
				{"spawn"
					{entity "conquest_spawn_helper"}
					{waypoint "0"}
					{disable_random_spawn_position}
				}
				{"delay"
					{time 0.01}
				}
				{"entity_state"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{amount 1
						}
						{tag conquest_spawn_helper}
					}
					{tag_add _default_b2}
					{tag_remove conquest_spawn_helper}
				}
				{"delay"
					{time 0.05}
				}
				{"placement"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{tag _default_b2}
					}
					{target
						{ignore_captured_by_user 0}
						{tag b2}
					}
				}
				{"spawn"
					{entity "conquest_spawn_helper"}
					{waypoint "0"}
					{disable_random_spawn_position}
				}
				{"delay"
					{time 0.01}
				}
				{"entity_state"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{amount 1
						}
						{tag conquest_spawn_helper}
					}
					{tag_add _default_b3}
					{tag_remove conquest_spawn_helper}
				}
				{"delay"
					{time 0.05}
				}
				{"placement"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{tag _default_b3}
					}
					{target
						{ignore_captured_by_user 0}
						{tag b3}
					}
				}
				{"spawn"
					{entity "conquest_spawn_helper"}
					{waypoint "0"}
					{disable_random_spawn_position}
				}
				{"delay"
					{time 0.01}
				}
				{"entity_state"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{amount 1
						}
						{tag conquest_spawn_helper}
					}
					{tag_add _default_b4}
					{tag_remove conquest_spawn_helper}
				}
				{"delay"
					{time 0.05}
				}
				{"placement"
					{selector
						{source standart}
						{ignore_captured_by_user 0}
						{tag _default_b4}
					}
					{target
						{ignore_captured_by_user 0}
						{tag b4}
					}
				}
			}