	{Entity "pe2_205" 0xc027
		{Position -4386.35 -9172.86}
		{xform zl 89.12}
		{TexMod "camo2"}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{Volume "spin2"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 319}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb1"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 47}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Human "mp/rus/mid/pilot" 0xc02c
		{Position -4385.32 -9106.06}
		{xform zl 89.12}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 320}
		{NameId 38 305}
		{LastItem "tt33"}
	}
	{Entity "i16" 0x8000
		{Position -4401.84 -9782.72}
		{xform zl 91.66}
		{DisableObstacles}
		{Player 0}
		{MID 1}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb1"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 40}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Human "mp/rus/mid/pilot" 0x8001
		{Position -4401.13 -9807.07}
		{xform zl 91.66}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 2}
		{NameId 109 189}
		{LastItem "tt33"}
	}
	{Entity "il2_mod42_rs" 0xc000
		{Position -4396.02 -9488.7}
		{xform zl 88.24}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}{nowounddecal 0}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 3}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "rocket"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 40}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Human "mp/rus/mid/pilot" 0xc001
		{Position -4398.04 -9494.23}
		{xform zl 88.24}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 4}
		{NameId 60 71}
		{LastItem "tt33"}
	}
	{Entity "p47_d22_hvar" 0xc002
		{Position -4418 -10417.2}
		{xform zl 88.48}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 5}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "rocket"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 40}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Entity "p47_d22_m8" 0xc003
		{Position -4415.62 -10106.3}
		{xform zl 88.48}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 6}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "rocket"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 40}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Human "mp/usa/late/pilot" 0xc004
		{Position -4415.82 -10104.3}
		{xform zl 180 y 4.05 zw -91.51}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 7}
		{NameId 73 48}
		{LastItem "m1911"}
	}
	{Human "mp/usa/late/pilot" 0xa001
		{Position -4418.2 -10415.2}
		{xform zl 180 y 4.05 zw -91.51}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 8}
		{NameId 23 67}
		{LastItem "m1911"}
	}
	{Entity "fi156" 0x8003
		{Position -4092.62 -9783.09}
		{xform zl 88.4}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 10}
		{Able "-emit_passangers_on_enemy"}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 40}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Entity "gladiator_mk2" 0x8004
		{Position -4112.06 -10110.9}
		{xform zl 88.4}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 11}
		{Able "-emit_passangers_on_enemy"}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 40}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Entity "po2" 0x8005
		{Position -4134.35 -10455.9}
		{xform zl 88.4}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 12}
		{Able "-emit_passangers_on_enemy"}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 40}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Human "mp/fin/early/pilot" 0x8006
		{Position -4112.05 -10110.6}
		{xform zl 88.4}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 13}
		{NameId 18 71}
		{LastItem "hipower_1935"}
	}
	{Human "mp/ger/mid/pilot" 0x800a
		{Position -4091.86 -9756.05}
		{xform zl 88.4}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 15}
		{NameId 132 48}
		{LastItem "luger"}
	}
	{Human "mp/rus/mid/pilot" 0x800e
		{Position -4133.57 -10428}
		{xform zl 88.4}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 17}
		{NameId 120 87}
		{LastItem "tt33"}
	}
	{Entity "blenheim_mk1_eng" 0x8007
		{Position -3969.23 -9169.54}
		{xform zl 89.21}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{Volume "spin2"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 19}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb1"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 40}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Entity "typhoon_mk1b" 0x800d
		{Position -3876.42 -10435.8}
		{xform zl 89.21}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade4"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 22}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb1"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 40}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Entity "hurribomber_mk2c" 0x8010
		{Position -3855.31 -10125.1}
		{xform zl 89.21}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 23}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb1"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 40}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Human "mp/eng/mid/pilot" 0xc005
		{Position -3876.35 -10421.6}
		{xform zl 180 y 3.76 zw -90.78}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 20}
		{NameId 153 21}
		{LastItem "enfield_no2_mk1"}
	}
	{Human "mp/eng/mid/pilot" 0xc007
		{Position -3855.19 -10125.8}
		{xform zl 180 y 3.76 zw -90.78}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 21}
		{NameId 147 16}
		{LastItem "enfield_no2_mk1"}
	}
	{Human "mp/eng/mid/pilot" 0xc009
		{Position -3963.58 -9119.33}
		{xform zl 89.21}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 24}
		{NameId 128 148}
		{LastItem "enfield_no2_mk1"}
	}
	{Entity "bf110_e2" 0x8009
		{Position -3636.69 -9240.22}
		{xform zl 89.94}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{Volume "spin2"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 25}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 47}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Human "mp/ger/mid/pilot" 0x800b
		{Position -3636.77 -9190.86}
		{xform zl 89.94}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "hand1l"
			{able {blast 0}}
		}
		{Volume "hand2l"
			{able {blast 0}}
		}
		{Volume "hand1r"
			{able {blast 0}}
		}
		{Volume "hand2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 26}
		{NameId 90 117}
		{LastItem "luger"}
	}
	{Link 0xc02c {0xc027 "driver"}} ;//pe2
	{Link 0x8001 {0x8000 "driver"}} ;//i16
	{Link 0xc001 {0xc000 "driver"}} ;//il2 rockets
	{Link 0x800e {0x8005 "driver"}} ;//po2
	
	{Link 0xa001 {0xc002 "driver"}} ;//p47 rockets hvar
	{Link 0xc004 {0xc003 "driver"}} ;//p47 rockets m8
	
	{Link 0x800a {0x8003 "driver"}} ;//fi156 recon
	{Link 0x800b {0x8009 "driver"}} ;//bf110 250
	
	{Link 0x8006 {0x8004 "driver"}} ;//gladiator recon

	{Link 0xc009 {0x8007 "driver"}} ;//blenheim
	{Link 0xc005 {0x800d "driver"}} ;//typhoon
	{Link 0xc007 {0x8010 "driver"}} ;//hurribomber

	{Tags "engine_count_2" "hidden" "air_vehicle" "no_scavenge" "move_fast" "airstrike_rus_500" "set_texmod" 0xc027}
	{Tags "pilot" 0xc02c}
	{Tags "engine_count_1" "hidden" "air_vehicle" "no_scavenge" "move_fast" "airstrike_rus_50" "set_texmod" 0x8000}
	{Tags "pilot" 0x8001}
	{Tags "engine_count_1" "hidden" "air_vehicle" "no_scavenge" "move_fast" "airstrike_rus_rocket" 0xc000}
	{Tags "pilot" 0xc001}
	{Tags "engine_count_1" "hidden" "move_fast" "no_scavenge" "air_vehicle" "airstrike_usa_rocket_hvar" 0xc002}
	{Tags "engine_count_1" "hidden" "move_fast" "no_scavenge" "air_vehicle" "airstrike_usa_rocket_m8" 0xc003}
	{Tags "pilot" 0xc004}
	{Tags "pilot" 0xa001}
	{Tags "engine_count_1" "hidden" "no_scavenge" "move_fast" "air_vehicle" "recon_plane" "airstrike_ger_recon" 0x8003}
	{Tags "engine_count_1" "set_texmod" "hidden" "no_scavenge" "move_fast" "air_vehicle" "recon_plane" "airstrike_fin_recon" 0x8004}
	{Tags "engine_count_1" "hidden" "no_scavenge" "move_fast" "air_vehicle" "recon_plane" "airstrike_rus_recon" 0x8005}
	{Tags "pilot" 0x8006}
	{Tags "pilot" 0x800a}
	{Tags "pilot" 0x800e}
	{Tags "engine_count_2" "airstrike_eng_250_2" "hidden" "air_vehicle" "move_fast" "no_scavenge" 0x8007}
	{Tags "engine_count_1" "airstrike_eng_250" "hidden" "air_vehicle" "move_fast" "no_scavenge" 0x800d}
	{Tags "engine_count_1" "airstrike_eng_100" "hidden" "air_vehicle" "move_fast" "no_scavenge" 0x8010}
	{Tags "pilot" 0xc005}
	{Tags "pilot" 0xc007}
	{Tags "pilot" 0xc009}
	{Tags "engine_count_2" "hidden" "airstrike_ger_250" "air_vehicle" "move_fast" "no_scavenge" 0x8009}
	{Tags "pilot" 0x800b}
